example:
  property: I AM THE DEV


spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL

eureka:
   instance:
      preferIpAddress: true
   client:
      registerWithEureka: true # Tells spring to register this project/service to eureka (to specified url)
      fetchRegistry: true # cache the request (so that it won't request to eureka, if the cache information is available). It will refresh the cache every 30 seconds
      serviceUrl: 
        defaultZone: http://localhost:8070/eureka/

keycloak:
  # Specify the realm
  realm: microservice_authorization_server
  # The auth endpoint for keycloak
  auth-server-url: http://localhost:9999/auth
  # Client id
  resource: microservices_authorization_server	
  # Credentials from client id
  credentials:
    secret: daxV01UoObJY44mGyeNYhfkzOUHanjCh
  use-resource-role-mappings: true
  bearer-only: true
